# yml file copied from monthly report GitHub action

on:
  push:
    branches: main
    
name: exhaustive model selection

jobs:
  knit:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    
    steps:
      - uses: actions/checkout@v3
    
      - uses: r-lib/actions/setup-pandoc@v2
    
      - uses: r-lib/actions/setup-r@v2
          
      - name: Install system dependencies
        run: brew install jags
        
      - name: Install dependencies
        run: |
          install.packages(c('runjags','tidyverse','data.table'))
          load("LIOW_SURV_INPUT.RData")
        shell: Rscript {0}
        
      - name: RUN MODEL SELECTION
        run: Rscript LIOW_telemetry_survival_model_selection.r
            
      - name: Commit results
        run: |
          git add LIOW_win_var_selection_DIC_table.csv
          git commit -m 'Model selection table produced' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
  
